name: Gradle Build

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      # Запускаем полную сборку проекта вместо одиночн2ого shadowJar
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
        
      # Публикуем готовый скомпилированный мод
      - name: Publish build
        uses: actions/upload-artifact@v3
        with:
          name: build
          # Собираем только финальные remapped файлы (исключая промежуточные -shadow и -sources)
          path: |
            build/libs/*.jar
            !build/libs/*-shadow.jar
            !build/libs/*-sources.jar