name: Сборка мода через Gradle

on:
  push:

jobs:
  build-gradle-project:
    name: Автоматическая сборка проекта
    runs-on: ubuntu-latest
    steps:
      - name: Проверка исходного кода (Checkout)
        uses: actions/checkout@v4
      
      - name: Настройка Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Настройка и кэширование Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Выдача прав на исполнение для Gradle Wrapper
        run: chmod +x gradlew
        
      - name: Сборка мода (Запуск Gradle Wrapper)
        run: ./gradlew build
        
      - name: Загрузка готового мода (.JAR артифакта)
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-Bridge-1.18.2
          path: build/libs/*.jar